Develop
Grigory8778/Jobik pull request #4
Opened 2021-09-06 08:09 UTC by Grigory8778

ViewModel

2021-09-07 10:45 UTC, dserbin96 requested changes

2021-09-07 10:45 UTC, dserbin96 commented on app/build.gradle
> +// Koin Java Compatibility
выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="com.example.jobik.SheetActivity"/>
возможно стоит задумать о том чтобы убрать альбомный режим и остамитьт только портретный

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/Home/sheet/BottomSheetFragment.kt
> +class BottomSheetFragment:BottomSheetDialogFragment() {
выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/data/ElementsRepository.kt
> +
отступы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/data/ElementsRepositoryImpl.kt
> +):ElementsRepository  {
выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/data/ResourceProvider.kt
> +    fun getColor(resId: Int)= ContextCompat.getColor(context,resId)
выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/data/TimeRepository.kt
> +
лишний отступ

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/data/TimeRepositoryImpl.kt
> +
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/addonbord/AddListOnbordFragment.kt
> +
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/addonbord/AddListOnbordFragment.kt
> +            viewModel.insert(1, "Дом")
хардкод, либо убрать в константу или брать через ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/addonbord/AddListOnbordView.kt
> +    fun showList(List:List<Item>)
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/addonbord/AddListOnbordViewModel.kt
> +    init {
инит должна быть между функциями и обьявлением переменных

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/base/App.kt
> +//    lateinit var resourceProvider: ResourceProvider
удали закоментированный код

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/base/RecResult.kt
> +sealed class Item {
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/hellionbord/OnboardHelleStepFragmetOne.kt
> +class OnboardHelleStepFragmetOne:Fragment() {
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/hellionbord/OnboardHelleStepFragmetSecond.kt
> +    }
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/hellionbord/OnboardHelloStepFragmetThird.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/hellionbord/OnboardHelloStepFragmetThird.kt
> +            viewModel.getHelloToAddScreens()
get - получить обозначаетс, называй функции правильно, в данном случае пиши openHelloToAddScreens

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/home/HomeFragment.kt
> +        return inflater.inflate(R.layout.home_main, container, false)
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/home/HomeViewModel.kt
> +    fun getHomeToSheet() {
переименовать

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/main/MainActivity.kt
> +        presenter.getOpenHome()
удали презентер и перенеси всю логику во ViewModel

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/main/MainViewModel.kt
> +    fun getOpenHome() {
переименуй openHome

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/main/RecMainAdapter.kt
> +
отступы, выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/navigation/Screens.kt
> +
отступы, вырвнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/onbord/OnbordActivity.kt
> +class OnbordActivity : AppCompatActivity() {
отступы, вырвнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/navigation/Screens.kt
> +    fun getHelloThirdScreen() = FragmentScreen { OnboardHelloStepFragmetThird() }
неправильное назщвание, должно быть Fragment/Activity на конце то есть должно быть OnboardHelloStepThirdFragmet

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/time/TimeOnbordFragment.kt
> +   fun setMin(mint: Int) {
где у тебя используется эта функция? думавю экран работает некоректно

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/main_cont"
main_container

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/add_category.xml
> +        app:title="Название" />
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginTop="32dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginStart="72dp"
в ресурсы, для чего такой большой отступ?

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:textSize="16sp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_width="24dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_height="24dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginStart="20dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginTop="37dp"
в ресурсы. отступ должен быть четным

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:id="@+id/textView1"
выравнивание

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginStart="72dp"
в ресурсы, для чего такой большой отступ?

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:textSize="16sp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_width="24dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_height="24dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_margin="20dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +        android:layout_width="300dp"
в ресурсы, для чего этот хардкод?

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_margin="16dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:textSize="24sp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +
отступ

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="56dp"
в ресурсы для чего такой большой отступ?

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:text="Дом"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:textSize="16sp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="18dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="56dp"
в ресурсы для чего такой большой отступ?

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="18dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:textSize="16sp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="56dp"
в ресурсы для чего такой большой отступ?

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="22dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +
отступ

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/drawer_layout.xml
> +            app:title="Дом" />
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/empty_cont.xml
> +        android:textSize="20sp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/empty_cont.xml
> +        android:text="Нажмите “+”, чтобы добавить действие"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/empty_cont.xml
> +        android:textSize="14sp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/home_main.xml
> +        app:title="Дом" />
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_one.xml
> +        android:text="ДАЛЬШЕ"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_one.xml
> +        android:textSize="22dp"
почему dp?в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_one.xml
> +        android:layout_marginStart="18dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_one.xml
> +        android:layout_marginEnd="18dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_second.xml
> +        android:text="ДАЛЬШЕ"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_second.xml
> +        android:textSize="22dp"
в ресурсы, почуму dp?

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_second.xml
> +        android:layout_marginStart="18dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_second.xml
> +        android:layout_marginEnd="18dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:text="ДАЛЬШЕ"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:textSize="22dp"
в ресурсы почему дп?

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:layout_marginStart="18dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:layout_marginEnd="18dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:text="Пропустить"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:layout_width="371dp"
в ресурсы, зачем хардкод? должны быть четными значения

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:layout_height="316dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/rec_item_one.xml
> +        android:layout_width="24dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/rec_item_one.xml
> +        android:layout_height="24dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/rec_main_item.xml
> +        android:layout_width="24dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/rec_main_item.xml
> +        android:layout_height="24dp"
в ресурсы

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/layout/seet_main.xml
> +        android:text="Button"
в ресурсы другое название

2021-09-07 10:45 UTC, dserbin96 commented on app/src/main/res/menu/menu_category.xml
> +        android:title="TODO" />
в ресурсы измени название

2021-09-07 11:15 UTC, Grigory8778 commented on app/build.gradle
> +// Koin Java Compatibility
+

2021-09-07 11:15 UTC, Grigory8778 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="com.example.jobik.SheetActivity"/>
+

2021-09-07 12:06 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/Home/sheet/BottomSheetFragment.kt
> +class BottomSheetFragment:BottomSheetDialogFragment() {
+

2021-09-07 12:07 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/data/ElementsRepository.kt
> +
+

2021-09-07 12:07 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/data/ElementsRepositoryImpl.kt
> +):ElementsRepository  {
+

2021-09-07 12:09 UTC, Grigory8778 commented on app/src/main/res/layout/rec_item_one.xml
> +        android:layout_height="24dp"
+

2021-09-07 12:10 UTC, Grigory8778 commented on app/src/main/res/layout/rec_main_item.xml
> +        android:layout_width="24dp"
+

2021-09-07 12:10 UTC, Grigory8778 commented on app/src/main/res/layout/rec_main_item.xml
> +        android:layout_height="24dp"
+

2021-09-07 12:13 UTC, Grigory8778 commented on app/src/main/res/menu/menu_category.xml
> +        android:title="TODO" />
+

2021-09-07 12:14 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/data/ResourceProvider.kt
> +    fun getColor(resId: Int)= ContextCompat.getColor(context,resId)
+

2021-09-07 12:15 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/data/TimeRepository.kt
> +
Исправил

2021-09-07 12:15 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/data/TimeRepositoryImpl.kt
> +
Исправил

2021-09-07 12:16 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/addonbord/AddListOnbordFragment.kt
> +
Исправил

2021-09-07 12:23 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/addonbord/AddListOnbordFragment.kt
> +            viewModel.insert(1, "Дом")
Исправил. Положил в ресурсы

2021-09-07 12:24 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/addonbord/AddListOnbordView.kt
> +    fun showList(List:List<Item>)
Удалил вью так как есть ViewModel

2021-09-07 12:24 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/addonbord/AddListOnbordViewModel.kt
> +    init {
Перенес

2021-09-07 12:25 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/base/App.kt
> +//    lateinit var resourceProvider: ResourceProvider
Удалил

2021-09-07 12:26 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/base/RecResult.kt
> +sealed class Item {
оставил 1 отступ между классом и пакетом

2021-09-07 12:27 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/hellionbord/OnboardHelleStepFragmetOne.kt
> +class OnboardHelleStepFragmetOne:Fragment() {
Исправил

2021-09-07 12:27 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/hellionbord/OnboardHelleStepFragmetSecond.kt
> +    }
Исправил

2021-09-07 12:27 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/hellionbord/OnboardHelloStepFragmetThird.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
Исправил

2021-09-07 12:29 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/hellionbord/OnboardHelloStepFragmetThird.kt
> +            viewModel.getHelloToAddScreens()
Исправил

2021-09-07 12:29 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/home/HomeFragment.kt
> +        return inflater.inflate(R.layout.home_main, container, false)
Исправил

2021-09-07 12:31 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/home/HomeViewModel.kt
> +    fun getHomeToSheet() {
Переименовал

2021-09-07 12:31 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/main/MainActivity.kt
> +        presenter.getOpenHome()
Удалил

2021-09-07 12:32 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/main/MainViewModel.kt
> +    fun getOpenHome() {
Переименовал

2021-09-07 12:33 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/main/RecMainAdapter.kt
> +
Исправил

2021-09-07 12:34 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/navigation/Screens.kt
> +
Исправил

2021-09-07 12:35 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/onbord/OnbordActivity.kt
> +class OnbordActivity : AppCompatActivity() {
Исправил

2021-09-07 12:37 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/navigation/Screens.kt
> +    fun getHelloThirdScreen() = FragmentScreen { OnboardHelloStepFragmetThird() }
Переименовал

2021-09-07 12:38 UTC, Grigory8778 commented on app/src/main/java/com/example/jobik/presentation/time/TimeOnbordFragment.kt
> +   fun setMin(mint: Int) {
Не используется .Удалил

2021-09-07 12:39 UTC, Grigory8778 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/main_cont"
Исправил

2021-09-07 12:40 UTC, Grigory8778 commented on app/src/main/res/layout/add_category.xml
> +        app:title="Название" />
Исправил

2021-09-07 12:42 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginTop="32dp"
+

2021-09-07 12:43 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginStart="72dp"
Делал по дизайну

2021-09-07 12:45 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginStart="20dp"
+

2021-09-07 12:45 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_height="24dp"
+

2021-09-07 12:45 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_width="24dp"
+

2021-09-07 12:45 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:textSize="16sp"
+

2021-09-07 12:45 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginTop="37dp"
+

2021-09-07 12:46 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_marginStart="72dp"
Делал по дизайду

2021-09-07 12:46 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:textSize="16sp"
+

2021-09-07 12:46 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_width="24dp"
+

2021-09-07 12:46 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_height="24dp"
+

2021-09-07 12:46 UTC, Grigory8778 commented on app/src/main/res/layout/bottomsheet.xml
> +        android:layout_margin="20dp"
+

2021-09-07 12:47 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +        android:layout_width="300dp"
Делал по дизайну

2021-09-07 12:48 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_margin="16dp"
+

2021-09-07 12:48 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:textSize="24sp"
+

2021-09-07 12:49 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +
+

2021-09-07 12:49 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="56dp"
Дизайн

2021-09-07 12:50 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:text="Дом"
+

2021-09-07 12:50 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:textSize="16sp"
+

2021-09-07 12:50 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="18dp"
+

2021-09-07 12:50 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="56dp"
Дизайн

2021-09-07 12:50 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="18dp"
+

2021-09-07 12:50 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:textSize="16sp"
+

2021-09-07 12:50 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="56dp"
Дизайн

2021-09-07 12:53 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            android:layout_marginStart="22dp"
+

2021-09-07 12:54 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +
+

2021-09-07 12:54 UTC, Grigory8778 commented on app/src/main/res/layout/drawer_layout.xml
> +            app:title="Дом" />
+

2021-09-07 12:55 UTC, Grigory8778 commented on app/src/main/res/layout/empty_cont.xml
> +        android:textSize="20sp"
+

2021-09-07 12:55 UTC, Grigory8778 commented on app/src/main/res/layout/empty_cont.xml
> +        android:text="Нажмите “+”, чтобы добавить действие"
+

2021-09-07 12:58 UTC, Grigory8778 commented on app/src/main/res/layout/empty_cont.xml
> +        android:textSize="14sp"
+

2021-09-07 12:58 UTC, Grigory8778 commented on app/src/main/res/layout/home_main.xml
> +        app:title="Дом" />
+

2021-09-07 13:00 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_one.xml
> +        android:text="ДАЛЬШЕ"
+

2021-09-07 13:00 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_one.xml
> +        android:textSize="22dp"
Исправил  на SP

2021-09-07 13:00 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_one.xml
> +        android:layout_marginStart="18dp"
+

2021-09-07 13:01 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_one.xml
> +        android:layout_marginEnd="18dp"
+

2021-09-07 13:03 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_second.xml
> +        android:text="ДАЛЬШЕ"
+

2021-09-07 13:03 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_second.xml
> +        android:textSize="22dp"
Исправли

2021-09-07 13:03 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_second.xml
> +        android:layout_marginStart="18dp"
+

2021-09-07 13:04 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:text="ДАЛЬШЕ"
+

2021-09-07 13:04 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:layout_marginStart="18dp"
Исправил

2021-09-07 13:04 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:layout_marginEnd="18dp"
+

2021-09-07 13:04 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:text="Пропустить"
+

2021-09-07 13:04 UTC, Grigory8778 commented on app/src/main/res/layout/onbord_hello_step_third.xml
> +        android:layout_height="316dp"
Картинки разные по размерам думал подогнать под один размер все

2021-09-07 13:05 UTC, Grigory8778 commented on app/src/main/res/layout/rec_item_one.xml
> +        android:layout_width="24dp"
+

2021-09-08 14:22 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/home/HomeFragment.kt
> +            listOf(
вынести в репозиторий

2021-09-08 14:22 UTC, dserbin96 commented on app/src/main/java/com/example/jobik/presentation/onbord/RecAdapter.kt
> +//       var state = list.filterIsInstance<Item.Elements>().filter { it.state }
удали коменты

2021-09-08 14:23 UTC, merged